export const SERVICES_END_POINTS = {
  get_service_categories_list: `api/services/service-category/`,
  get_service_in_demand_list: `api/home/event_service/`,
  get_category: `api/services/categories/`,
  get_service_questions: `api/services/service-questions/?service_id=`,
  get_services_detail: `api/services/service/?category_slug=`,
  post_service_recipient: "api/services/service-recipient/",
  post_service_time: "api/services/service-time/",
  post_order_description: "api/services/order-description/",
  post_service_questions: "api/services/answer/",
  get_expert_list: "api/orders/order-expert-list?order_id=",
  post_expert_prioritizing: "api/experts/expert-priortizing/",
  post_answers_question: "api/services/answer/",
  post_order_confirmation: "api/services/user-order-confirmation/",
  get_neighborhood_list: "api/users/neighborhood/?city_id=",
  get_search_category_services: "api/services/search/?query=",
  get_service_active: `api/services/service-active/`,
  post_check_discount_code: `api/discounts/discount-validation/`,
  get_history_search: `api/services/search-history/`,
  post_history_search: `api/services/search-history/`,
  post_increase_gift_credit: "api/discounts/credit-token/?token=",
};

export const HOME_END_POINTS = {
  get_slider: `api/home/sliders/?type_view=PHONE_SIZE`,
  event_service: `api/home/event_service/`,
  get_home_comments: `api/experts/home-comments/`,
};

export const PROFILE_END_POINTS = {
  get_profile: `api/users/profile/`,
  put_update_profile: `api/users/profile/`,
  get_all_faqs: `api/dashboards/faqs/`,
  get_profile_avatar: `api/users/profile-avatar/`,
  get_notifications: `api/notifications/`,
  get_avatar_list: `api/users/avatar-list/`,
  put_update_profile_avatar: `api/users/profile-avatar/`,
  post_increase_credit: `api/users/increase-credit-bazaarpay/`,
  get_invitation_code: "api/users/create_invitation/",
};

export const ORDER_END_POINTS = {
  get_expert_order_list: `api/orders/expert-order-list`,
  get_expert_order_detail: `api/orders/expert-order-detail`,
  get_user_order_list: `api/orders/user-order-list`,
  get_user_order_detail: `api/orders/user-order-detail`,
  get_deposit_data: `api/orders/deposit-offering`,
  post_expert_order_acceptance: `api/orders/expert-order-acceptance`,
  post_expert_order_rejecting: `api/orders/expert-order-rejecting`,
  post_user_order_canceling: `api/orders/user-order-canceling`,
  post_expert_order_starting: `api/orders/expert-order-starting`,
  post_invoice_offering: `api/orders/invoice-offering`,
  post_deposit_offering: `api/orders/deposit-offering`,
  post_payment: `api/orders/payment`,
  post_deposit_payment: `api/orders/deposit-payment`,
  get_order_by_track_id: `api/orders/order-by-trackid?track_id=`,
  get_Transactions: `api/orders/transactions`,
  get_user_transactions: `api/orders/user-transactions`,
  patch_order_guarantee: "api/orders/guaranteed-order",
  update_order_invoice: "api/orders/invoice-offering",
  get_orders_guaranteed: "api/orders/user-guaranteed-order-list",
  delete_user_order: `api/orders/user-order-delete`,
  post_user_order_select_expert: "api/orders/user-order-select-expert",
  expert_order_reject: "/api/orders/expert-order-reject",
  user_cancel_expert: "api/orders/user-order-cancel-expert",
};

export const ADDRESS_END_POINTS = {
  get_address_list: `api/users/addresses-list/`,
  get_address: `api/users/address/?id=`,
  put_update_address: `api/users/address/`,
  post_create_address: `api/users/address/`,
  del_delete_address: `api/users/address/`,
  get_search_city: `api/users/search-city/?search_value=`,
  get_province_list: `api/users/province/`,
  get_city_list: `api/users/city/?province_id=`,
};

export const EXPERT_END_POINT = {
  get_not_available_time: `api/experts/not-available-time/`,
  put_not_available_time: `api/experts/not-available-time/`,
  get_sample_list: `api/experts/my-sample-list/`,
  get_sample_details: `api/experts/sample/?id=`,
  post_create_sample: `api/experts/sample/`,
  put_update_sample: `api/experts/sample/`,
  delete_sample: `api/experts/sample/`,
  get_expert_profile: "api/experts/expert-profile/",
  put_update_expert: "api/experts/expert-detail/",
  get_experts_neighborhoods_list: "api/experts/neighborhoods-list/",
  get_experts_available_neighborhoods: "api/experts/available-neighborhoods/",
  put_update_neighborhood_expert: "api/experts/update-neighborhood-expert/",
  get_notifications: `api/notifications/expert-notification-list/`,
  get_expert_credit: `api/experts/credit/`,
  post_expert_early_sign_up: `api/experts/expert-early-sign-up/`,
  get_experts_specialty: `api/experts/specialty/`,
  get_expert_sample_list: `api/experts/sample-list/?expert_id=`,
  get_expert_detail: `api/experts/expert-detail/?expert_id=`,
  post_expert_increase_credit: `api/experts/increase-credit-bazaarpay/`,
  post_expert_comment: "api/experts/comment/",
  get_expert_comments: "api/experts/expert-comments/",
  post_expert_going_to_work: "api/orders/expert-going-to-work",
};
